// AUTO-GENERATED by scripts/build-catalog-images.mjs — do not edit by hand.
//
// Maps catalogue slugs to frontend-hosted image URLs (served from
// public/catalog/). These stand in for the backend /media/ paths, which are
// wiped whenever the API redeploys on Railway's ephemeral disk. Regenerate
// with: npm run catalog:images

export const itemImages = {
  "amber-adinkra-ankara-shirt": [
    "/catalog/2-54-10-0.jpeg"
  ],
  "ankara-his-hers-set": [
    "/catalog/2-54-45-0.jpeg",
    "/catalog/2-54-45-1.jpeg",
    "/catalog/2-54-45-2.jpeg"
  ],
  "ankara-stripe-shirt": [
    "/catalog/2-54-53-0.jpeg",
    "/catalog/2-54-53-1.jpeg",
    "/catalog/2-54-53-2.jpeg",
    "/catalog/2-54-53-3.jpeg"
  ],
  "brown-placket-two-piece": [
    "/catalog/2-54-35-0.jpeg",
    "/catalog/2-54-35-1.jpeg",
    "/catalog/2-54-35-2.jpeg",
    "/catalog/2-54-35-3.jpeg"
  ],
  "burgundy-adinkra-shirt": [
    "/catalog/2-54-05-0.jpeg",
    "/catalog/2-54-05-1.jpeg"
  ],
  "burgundy-blazer-dress": [
    "/catalog/2-53-43-0.jpeg"
  ],
  "burgundy-utility-shirt": [
    "/catalog/2-54-32-0.jpeg"
  ],
  "cathedral-adinkra-shirt": [
    "/catalog/2-54-34-0.jpeg",
    "/catalog/2-54-34-1.jpeg",
    "/catalog/2-54-34-2.jpeg"
  ],
  "charcoal-waffle-polo": [
    "/catalog/2-57-15-0.jpeg",
    "/catalog/2-57-15-1.jpeg",
    "/catalog/2-57-15-2.jpeg",
    "/catalog/2-57-15-3.jpeg"
  ],
  "cream-marble-native": [
    "/catalog/2-54-46-0.jpeg",
    "/catalog/2-54-46-1.jpeg",
    "/catalog/2-54-46-2.jpeg",
    "/catalog/2-54-46-3.jpeg"
  ],
  "crimson-print-overshirt": [
    "/catalog/2-54-36-0.jpeg",
    "/catalog/2-54-36-1.jpeg",
    "/catalog/2-54-36-2.jpeg"
  ],
  "emerald-adinkra-shirt": [
    "/catalog/2-54-08-0.jpeg"
  ],
  "emerald-gold-two-piece": [
    "/catalog/2-54-49-0.jpeg",
    "/catalog/2-54-49-1.jpeg"
  ],
  "emerald-laceup-kaftan": [
    "/catalog/2-53-51-0.jpeg",
    "/catalog/2-53-51-1.jpeg"
  ],
  "emerald-mandarin-shirt": [
    "/catalog/2-54-33-0.jpeg",
    "/catalog/2-54-33-1.jpeg",
    "/catalog/2-54-33-2.jpeg"
  ],
  "floral-resort-shirt": [
    "/catalog/2-53-52-0.jpeg",
    "/catalog/2-53-52-1.jpeg",
    "/catalog/2-53-52-2.jpeg",
    "/catalog/2-53-52-3.jpeg"
  ],
  "gold-folded-kaftan": [
    "/catalog/2-53-58-0.jpeg"
  ],
  "gold-kente-pocket-shirt": [
    "/catalog/2-54-24-0.jpeg"
  ],
  "golden-bridal-gown": [
    "/catalog/2-57-09-0.jpeg",
    "/catalog/2-57-09-1.jpeg",
    "/catalog/2-57-09-2.jpeg",
    "/catalog/2-57-09-3.jpeg"
  ],
  "graduation-lace-dress": [
    "/catalog/2-57-11-0.jpeg",
    "/catalog/2-57-11-1.jpeg",
    "/catalog/2-57-11-2.jpeg",
    "/catalog/2-57-11-3.jpeg"
  ],
  "his-hers-signature-set": [
    "/catalog/2-54-44-0.jpeg",
    "/catalog/2-54-44-1.jpeg",
    "/catalog/2-54-44-2.jpeg",
    "/catalog/2-54-44-3.jpeg"
  ],
  "horseshoe-applique-shirt": [
    "/catalog/2-53-48-0.jpeg",
    "/catalog/2-53-48-1.jpeg"
  ],
  "ivory-medallion-two-piece": [
    "/catalog/2-54-51-0.jpeg",
    "/catalog/2-54-51-1.jpeg",
    "/catalog/2-54-51-2.jpeg",
    "/catalog/2-54-51-3.jpeg"
  ],
  "kente-corset-gown": [
    "/catalog/2-54-37-0.jpeg",
    "/catalog/2-54-37-1.jpeg",
    "/catalog/2-54-37-2.jpeg",
    "/catalog/2-54-37-3.jpeg"
  ],
  "kente-peplum-gown": [
    "/catalog/2-57-08-0.jpeg",
    "/catalog/2-57-08-1.jpeg"
  ],
  "knust-75th-anniversary-shirt": [
    "/catalog/2-54-11-0.jpeg"
  ],
  "knust-heritage-shirt": [
    "/catalog/2-54-15-0.jpeg"
  ],
  "knust-heritage-shirt-ii": [
    "/catalog/2-54-18-0.jpeg"
  ],
  "magenta-ankara-girls-dress": [
    "/catalog/2-54-54-0.jpeg"
  ],
  "mosaic-print-two-piece": [
    "/catalog/2-57-13-0.jpeg",
    "/catalog/2-57-13-1.jpeg",
    "/catalog/2-57-13-2.jpeg"
  ],
  "mustard-kente-pocket-shirt": [
    "/catalog/2-54-23-0.jpeg"
  ],
  "mustard-mandarin-kaftan": [
    "/catalog/2-54-01-0.jpeg"
  ],
  "navy-batik-shirt": [
    "/catalog/2-54-41-0.jpeg",
    "/catalog/2-54-41-1.jpeg",
    "/catalog/2-54-41-2.jpeg",
    "/catalog/2-54-41-3.jpeg"
  ],
  "navy-blazer-dress": [
    "/catalog/2-53-45-0.jpeg",
    "/catalog/2-53-45-1.jpeg"
  ],
  "navy-db-suit": [
    "/catalog/2-54-42-0.jpeg",
    "/catalog/2-54-42-1.jpeg",
    "/catalog/2-54-42-2.jpeg"
  ],
  "navy-stripe-polo": [
    "/catalog/2-54-43-0.jpeg",
    "/catalog/2-54-43-1.jpeg",
    "/catalog/2-54-43-2.jpeg"
  ],
  "nude-mermaid-gown": [
    "/catalog/2-53-55-0.jpeg"
  ],
  "olive-kente-native": [
    "/catalog/2-54-47-0.jpeg",
    "/catalog/2-54-47-1.jpeg",
    "/catalog/2-54-47-2.jpeg"
  ],
  "onyx-cape-gown": [
    "/catalog/2-53-46-0.jpeg",
    "/catalog/2-53-46-1.jpeg"
  ],
  "onyx-zigzag-two-piece": [
    "/catalog/2-54-50-0.jpeg",
    "/catalog/2-54-50-1.jpeg",
    "/catalog/2-54-50-2.jpeg"
  ],
  "palm-resort-shirt": [
    "/catalog/2-57-14-0.jpeg",
    "/catalog/2-57-14-1.jpeg",
    "/catalog/2-57-14-2.jpeg",
    "/catalog/2-57-14-3.jpeg"
  ],
  "pinstripe-grad-suit": [
    "/catalog/2-54-38-0.jpeg",
    "/catalog/2-54-38-1.jpeg",
    "/catalog/2-54-38-2.jpeg",
    "/catalog/2-54-38-3.jpeg"
  ],
  "red-abstract-boys-set": [
    "/catalog/2-57-16-0.jpeg",
    "/catalog/2-57-16-1.jpeg"
  ],
  "regal-gold-agbada": [
    "/catalog/2-57-10-0.jpeg",
    "/catalog/2-57-10-1.jpeg",
    "/catalog/2-57-10-2.jpeg",
    "/catalog/2-57-10-3.jpeg"
  ],
  "royal-mudcloth-shirt": [
    "/catalog/2-54-39-0.jpeg",
    "/catalog/2-54-39-1.jpeg",
    "/catalog/2-54-39-2.jpeg"
  ],
  "savanna-abstract-shirt": [
    "/catalog/2-54-52-0.jpeg",
    "/catalog/2-54-52-1.jpeg",
    "/catalog/2-54-52-2.jpeg"
  ],
  "savanna-abstract-two-piece": [
    "/catalog/2-57-12-0.jpeg",
    "/catalog/2-57-12-1.jpeg",
    "/catalog/2-57-12-2.jpeg",
    "/catalog/2-57-12-3.jpeg"
  ],
  "scarlet-ankara-corset": [
    "/catalog/2-53-57-0.jpeg"
  ],
  "sky-adinkra-panelled-shirt": [
    "/catalog/2-54-09-0.jpeg"
  ],
  "tan-ankara-native": [
    "/catalog/2-54-48-0.jpeg",
    "/catalog/2-54-48-1.jpeg",
    "/catalog/2-54-48-2.jpeg"
  ],
  "teal-contrast-kaftan": [
    "/catalog/2-54-40-0.jpeg",
    "/catalog/2-54-40-1.jpeg",
    "/catalog/2-54-40-2.jpeg"
  ]
};

export const categoryImages = {
  "couple-sets": "/catalog/2-54-45-0.jpeg",
  "kids": "/catalog/2-54-54-0.jpeg",
  "kids-boys": "/catalog/2-57-16-0.jpeg",
  "kids-girls": "/catalog/2-54-54-0.jpeg",
  "men": "/catalog/2-54-05-0.jpeg",
  "mens-agbada": "/catalog/2-57-10-0.jpeg",
  "mens-kaftans": "/catalog/2-53-51-0.jpeg",
  "mens-native": "/catalog/2-54-49-0.jpeg",
  "mens-polos": "/catalog/2-54-43-0.jpeg",
  "mens-shirts": "/catalog/2-54-11-0.jpeg",
  "women": "/catalog/2-53-46-0.jpeg",
  "womens-ankara": "/catalog/2-53-57-0.jpeg",
  "womens-bridal": "/catalog/2-57-09-0.jpeg",
  "womens-corporate": "/catalog/2-54-42-0.jpeg",
  "womens-gowns": "/catalog/2-53-55-0.jpeg",
  "womens-kente": "/catalog/2-54-37-0.jpeg"
};
